### ISSUE TITLE
scribe hangs indefinitely on single threaded JVM

### ISSUE THREAD

**Issue by ngbinh** [outr/scribe#145]
https://github.com/outr/scribe/blob/cc4d70161ba3588ba45149bd989393a779c3cac4/core/jvm/src/main/scala/scribe/Platform.scala#L17 means it would hang indefinitely on single threaded JVM. I see the issue when running on CI where I set `parallelExecution := false`.

**Comment by darkfrog26** [comment]
Hmm, I hadn't considered that scenario. Do you have any thoughts on addressing it? I'm not a fan of `Await`, but this is necessary to make sure that any modules necessary for Scribe have properly loaded before continuing. I would usually just do it all asynchronously, but logging defaults to synchronous.

**Comment by ngbinh** [comment]
I haven't been able to dig deeper on why that `Await` hangs definitely. Is there a way to make sure it will not hang even on single theaded? Otherwise, it is too dangerous

**Comment by darkfrog26** [comment]
Honestly, I have very little experience with single-threaded runtimes. I'll have to look into this further.

**Comment by ngbinh** [comment]
I am seeing this problem on all of our integ test on CI with scribe newer than `3.1.0`. Will try to see if I can reproduce it

**Comment by darkfrog26** [comment]
The integration with `Moduload` was added around that time.

**Comment by darkfrog26** [comment]
I'm changing how `Moduload` works so that it is no longer asynchronous and I'll get a new release of Scribe out with it.

**Comment by ngbinh** [comment]
Great, thanks and happy holiday!

**Comment by darkfrog26** [comment]
@ngbinh I've made the change to `Moduload`, but I'm hung up on a dependency I need to fix before I can get another release out. I'll update this ticket when it's finished.

**Comment by ngbinh** [comment]
@darkfrog26 Do you know of any work around for this issue on `3.1.8`?

**Comment by darkfrog26** [comment]
Sorry it is taking so long to get a new release. Scribe is waiting on Profig is waiting on uPickle is waiting on Geny is waiting on uTest (https://github.com/lihaoyi/utest/issues/226). As soon as that issue is resolved I should be able to get a new release out quickly.

As far as a workaround, you may be able to do something like:
```scala
val future = Moduload.load()(Execution.global)
while (!future.isComplete) {
  Thread.sleep(100)
}
```
Before you make any call to Scribe. This should allow the future to complete successfully before the `Await` is invoked, and I believe if the future is already completed before it gets there, the `Await` won't block at all.

However, I'm not really sure how this will work for the single-threaded scenario.

**Comment by ngbinh** [comment]
@darkfrog26 thanks for the update and the tip. Will try it

**Comment by darkfrog26** [comment]
Let me know if it works and I'll update this ticket as soon as I'm able to get a new release out.

**Comment by darkfrog26** [comment]
@ngbinh sorry for the delays. I was intending to roll this out with 3.2, but it got a bit out of control as I'm completely re-writing file logging support. However, I just did a new release (`3.1.9`) that gives you the ability to call `scribe.Platform.initModuload = false` before you do anything and it should skip the `Await` entirely. In `3.2` this issue is completely removed, but it might be a while longer before I'm about to get it released.

Also, hopefully you don't need Dotty support as this release excludes it.

**Comment by ngbinh** [comment]
@darkfrog26 thanks, will try it out

**Comment by ngbinh** [comment]
Confirm that it works if I have `scribe.Platform.initModuload = false` before. Thanks

**Comment by darkfrog26** [comment]
@ngbinh awesome...as soon as 3.2 is released that will be unnecessary.

**Comment by darkfrog26** [comment]
Scribe 3.2.0 is now available which should make this a non-issue.

**Comment by ngbinh** [comment]
awesome! Will update
