### ISSUE TITLE
MDC syntax improvement 

### ISSUE THREAD

**Issue by fmeriaux** [outr/scribe#503]
Do you think it would be possible to add methods like `contextInfo` etc, which would make it possible to do something like: 

```scala
logger.contextInfo("my log message", context = Map("foo" -> "bar"))
```

?

This would be a syntactic sugar, encompassing the MDC statement inside; the latter can be quite cumbersome.

**Comment by darkfrog26** [comment]
I tend to re-write my code always to receive the implicit `MDC` as I showed above so it can propagate and be used properly in concurrency. Honestly, this isn't a problem I frequently have where I want to set information on a single log record, however, there is some general support.

You can use data-set on the logger:
```scala
logger.set("foo", "bar")
logger.info("my log message")
```

You can technically set the data upon creation of the `LogRecord`, but there's not a lot of great support for that.

I actually have an idea for an update to Scribe that might make stuff like this much better, but I need to think through it more. Instead of `logger.info(LoggableMessage*)`, I could change it to `logger.info(LogFeature*`) where `LogFeature` would interact with the creation of the `LogRecord` instead of solely being a message. This would allow data to be set, level to be boosted, timestamp to be overridden, MDC to be overridden, etc. Then you could do things like:
```scala
logger.info("my log message", data("foo" -> "bar"))
```

**Comment by fmeriaux** [comment]
It's great! Thanks a lot. 

Is it possible to support a `Map[String, Any]` as a valid input? 

```scala
val contextMap: Map[String, Any] = ???

logger.info("my log message", contextMap)

// ou encore  
logger.info("my log message", data(contextMap))
```

At present, it seems to me that only one key -> value can be passed.

**Comment by darkfrog26** [comment]
Try `3.12.1`: https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/package.scala#L36

**Comment by fmeriaux** [comment]
Great! Thanks a lot 👍
